version: '2'
services:
  app:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    working_dir: /app
    links:
      - redis

  redis:
    image: redis:3.2.3
